# Generated by Django 6.0 on 2026-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Jodi proyojon hoy image upload korun', null=True, upload_to='quiz_questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(help_text='1, 2, 3 or 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Apnar question ekhane likhun (code ba text)'),
        ),
    ]
