# Generated by Django 6.0 on 2026-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_image_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-score', '-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='dept',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uap_mail',
            field=models.EmailField(max_length=254, verbose_name='UAP Webmail'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], help_text='Sothik uttor select korun'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Chhobi ba diagram thakle upload korun', null=True, upload_to='quiz_questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt1',
            field=models.CharField(max_length=255, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.CharField(max_length=255, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.CharField(max_length=255, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.CharField(max_length=255, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Apnar question ba code ekhane likhun'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Checked thakle portal-e show korbe'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('quiz', 'student_id')},
        ),
    ]
