# Generated by Django 6.0 on 2026-04-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_participant_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['quiz', '-score']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='roll',
        ),
        migrations.AlterField(
            model_name='participant',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uap_mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
