# Generated by Django 6.0 on 2026-04-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_participant_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOneParticipant',
            fields=[
            ],
            options={
                'verbose_name': 'Quiz Wise Segment',
                'verbose_name_plural': '3. Quiz Wise Segments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz_app.participant',),
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['quiz', '-score'], 'verbose_name': 'All Participant', 'verbose_name_plural': '2. All Participants (Master List)'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': '1. Quizzes & Questions'},
        ),
    ]
