# Generated by Django 6.0 on 2026-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quizoneparticipant_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizOneParticipant',
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['quiz', '-score']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='participant',
            name='roll',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
