# Generated by Django 6.0 on 2026-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_delete_quizoneparticipant_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opt1_img',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='opt2_img',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='opt3_img',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='opt4_img',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
