# Generated by Django 6.0 on 2026-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('current_semester', models.CharField(choices=[('1-2', '1-2'), ('2-1', '2-1')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('motivation', models.TextField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('designing_skills', models.CharField(max_length=255)),
                ('video_editing', models.CharField(max_length=5)),
                ('extracurricular', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='Fall 2025', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('deadline', models.CharField(default='26 January, 2026', max_length=100)),
                ('message_if_closed', models.TextField(default='Please wait for Spring 2026 recruitment.')),
            ],
        ),
    ]
