# Generated by Django 6.0 on 2026-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Contest', 'Contest'), ('Seminar', 'Seminar'), ('General', 'General')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date_captured', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
