# Generated by Django 6.0 on 2026-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Quiz', 'Quiz'), ('Workshop', 'Workshop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='date_captured',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
