# Generated by Django 6.0 on 2026-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('MATH_OLYMPIAD', 'Math Olympiad'), ('PUZZLE_HUNT', 'Puzzle Hunt'), ('OTHER', 'Other Event')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_registration', models.DateTimeField()),
                ('end_registration', models.DateTimeField()),
                ('form_url', models.CharField(help_text='Link to the registration form', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
