# Generated by Django 6.0 on 2026-04-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_former_president', models.BooleanField(default=False)),
                ('tenure_year', models.CharField(blank=True, help_text='e.g. 2023', max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
