# Generated by Django 6.0 on 2026-04-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_remove_teammember_bio_teammember_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='linkedin',
            new_name='facebook',
        ),
    ]
