# Generated by Django 6.0 on 2026-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_rename_linkedin_teammember_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
